### ISSUE TITLE
Mark qualified / ranked maps in the beatmap listing

### ISSUE THREAD

**Issue by Endaris** [venix12/christmas-queue#22]
There's currently no way to tell qualified and ranked maps apart.
It should be visible to modders and BNs at first sight that there is no point in checking the map if it is ranked and probably less so compared to other sets if it is qualified.

**Comment by Endaris** [comment]
Ideally this would happen through API requests for all maps in set intervals to fetch the most recent map status and display it (graveyarded, pending, qualified, ranked, undefined would be enough I think)

A more simple approach would be just manually changing the status on the website. This should be possible for both ambassadors and the mapowner then (should be possible to implement since we log in with our osu! credentials so the userId should be known and can be checked against the map)

**Comment by venix12** [comment]
resolved via 010a654a4103e1c71f85ebca50f49750f67d9ed4
